version: "3.6"

services:
    xuexi:
        image: techxuexi/techxuexi-amd64:latest
        container_name: xuexi
        # 自动重启
        restart: always
        network_mode: bridge
        # 挂载目录
        volumes:
            - /opt/xuexi/user:/xuexi/user
            #- /opt/xuexi/static:/xuexi/static
            #- /opt/xuexi/pdlearn:/xuexi/pdlearn
        # 打开的端口
        ports:
            # 打开30080端口，访问 http://服务器ip:30080 进行控制
            - 30080:80
            - 30081:8088
        # 设置共享内存2g（shared memory）,减少chrome崩溃
        shm_size: 2gb
        # 环境变量
        environment:
            # 将在每天5：47和13：47及21：47自动运行一次学习，防止忘记点UID开始学习
            - CRONTIME=47 5,13,21 * * *
            # 每6小时运行一次
            # - CRONTIME=25 */6 * * *
            # 打开专项答题
            - ZhuanXiang=True
            # 信息推送模式：网页模式
            - Pushmode=6
            # 以下爱参数网页模式不需要，其他模式请根据实际情况修改
            # - "AccessToken={token}"
            # - "Secret={密钥}"
