version: "3.6"

services:
    techxuexi:
        image: techxuexi/techxuexi-amd64
        container_name: techxuexi-web
        # 自动重启
        restart: always
        # 挂载目录
        volumes:
            - /opt/xuexi/user:/xuexi/user
        # 打开的端口
        ports:
            # 打开30080端口，访问 http://服务器ip:30080 进行控制
            # 这个30081端口对应容器内8088是微信公众号控制端口，我预先映射出来了，免得你们再去查找
            - 9980:80
            - 9981:8088
        # 设置共享内存2g（shared memory）,减少chrome崩溃
        shm_size: 2gb
        # 环境变量
        environment:
            # 将在每天0：25和18：25自动运行一次学习，防止忘记点UID开始学习
            - CRONTIME=25 18,0 * * *
            # 每6小时运行一次
            # - CRONTIME=25 */6 * * *
            # 打开专项答题
            - ZhuanXiang=True
            # 信息推送模式：网页模式
=6 钉钉=1 微信=2 Server酱=3 pluspush=4 telegram
            - Pushmode=6
            # 以下爱参数网页模式不需要，其他模式请根据实际情况修改
            # - "AccessToken={token}"
            # - "Secret={密钥}"
            - Scheme=https://xuexi.llqxs.cn?url=
            # # 自定义拉取版本
            - Sourcepath=https://gitclone.com/github.com/TechXueXi/TechXueXi
